apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJmaXJzdG9uZTAxLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBxWm0xbFZtOWtRRlZ6WVRFek53PT0iCgkJfQoJfQp9                     
type: kubernetes.io/dockerconfigjson